workflows:
  ios-workflow:
    name: iOS Release Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "Allied Tajar"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        
    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get
          
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          
      - name: Create IPA
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r ../../../app.ipa Payload
          
    artifacts:
      - app.ipa
      - build/ios/iphoneos/*.app
      - flutter_drive.log
      
    publishing:
      email:
        recipients:
          - abdulzia@example.com
        notify:
          success: true
          failure: true